=== manarbajafar/Portfolio/Manar_Portfolio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Portfolio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="PersonalInfo" type="PersonalInfoType"/>
                <xs:element name="Education" type="EducationType"/>
                <xs:element name="Internships" type="InternshipsType"/>
                <xs:element name="Skills" type="SkillsType"/>
                <xs:element name="Projects" type="ProjectsType"/>
                <xs:element name="Publications" type="PublicationsType"/>
                <xs:element name="Volunteering" type="VolunteeringType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="PersonalInfoType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="JobTitle" type="xs:string"/>
            <xs:element name="Email" type="xs:string"/>
            <xs:element name="LinkedIn" type="xs:string"/>
            <xs:element name="GitHub" type="xs:string"/>
            <xs:element name="ProfilePicture" type="xs:string"/>
            <xs:element name="CV" type="xs:string"/>
            <xs:element name="Description" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="EducationType">
        <xs:sequence>
            <xs:element name="Degree" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="title" type="xs:string" use="required"/>
                    <xs:attribute name="university" type="xs:string" use="required"/>
                    <xs:attribute name="years" type="xs:string" use="required"/>
                    <xs:attribute name="honors" type="xs:string" use="optional"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="InternshipsType">
        <xs:sequence>
            <xs:element name="Internship" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="company" type="xs:string" use="required"/>
                    <xs:attribute name="position" type="xs:string" use="required"/>
                    <xs:attribute name="years" type="xs:string" use="required"/>
                    <xs:attribute name="location" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SkillsType">
        <xs:sequence>
            <xs:element name="SkillCategory" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Skill" maxOccurs="unbounded" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="title" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ProjectsType">
        <xs:sequence>
            <xs:element name="Project" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Description" type="xs:string"/>
                        <xs:element name="Technologies">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Technology" maxOccurs="unbounded" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="Logo" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="title" type="xs:string" use="required"/>
                    <xs:attribute name="duration" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PublicationsType">
        <xs:sequence>
            <xs:element name="Publication" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Link" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="title" type="xs:string" use="required"/>
                    <xs:attribute name="journal" type="xs:string" use="required"/>
                    <xs:attribute name="volume" type="xs:string" use="required"/>
                    <xs:attribute name="number" type="xs:string" use="optional"/>
                    <xs:attribute name="year" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VolunteeringType">
        <xs:sequence>
            <xs:element name="Role" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="organization" type="xs:string" use="required"/>
                            <xs:attribute name="year" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="Initiative" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== manarbajafar/Portfolio/Manar_Portfolio.xml
<?xml version="1.0" encoding="UTF-8"?> 
<?xml-stylesheet type="text/xsl" href="Manar_Portfolio.xsl"?>
<Portfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="Manar_Portfolio.xsd">

    <!-- Personal information -->
    <PersonalInfo>
        <Name>Manar Bajafar</Name>
        <JobTitle>Software Engineer</JobTitle>
        <Email>manar.bajafar@gmail.com</Email>
        <LinkedIn>https://www.linkedin.com/in/manarbajafar</LinkedIn>
        <GitHub>https://github.com/manarbajafar</GitHub>
        <ProfilePicture>assets/profile-pic.png</ProfilePicture>
        <CV>assets/Manar_Bajafar_CV.pdf</CV>
        <Description>Master’s student in Computer Science at King Abdulaziz University. Skilled in developing mobile applications using Flutter, working with databases such as MySQL, Firebase, and MongoDB, and understanding the Software Development Life Cycle (SDLC). Keen to learn more and face new challenges to gain experience.</Description>
    </PersonalInfo>

    

    <!-- Educational background -->
    <Education>
        <Degree title="Bachelor of Computer Science" university="Umm Al-Qura University" years="2018-2023" honors="First-Class Honors, 3.99/4 GPA"/>
        <Degree title="Master of Computer Science" university="King Abdulaziz University" years="2024-present"/>
    </Education>

    <!-- Internship experiences -->
    <Internships>
        <Internship company="First City" position="Frontend Developer Intern, Scrum Master" years="2024/07 – 2024/08" location="Makkah, Saudi Arabia"/>
        <Internship company="SeedLab" position="Database Specialist" years="2023/07 – present" location="Remotely"/>
        <Internship company="NERO" position="Mobile Application Developer Intern" years="2023/09 – 2023/11" location="Jeddah, Saudi Arabia"/>
    </Internships>

    <!-- Skills -->
    <Skills>
        <SkillCategory title="Databases">
            <Skill>MySQL</Skill>
            <Skill>Firebase</Skill>
            <Skill>MongoDB</Skill>
        </SkillCategory>
        <SkillCategory title="Programming &amp; Development">
            <Skill>Flutter</Skill>
            <Skill>Python</Skill>
            <Skill>Java</Skill>
            <Skill>Dart</Skill>
        </SkillCategory>
        <SkillCategory title="Tools &amp; Platforms">
            <Skill>Figma</Skill>
            <Skill>Git &amp; GitHub</Skill>
            <Skill>WordPress</Skill>
        </SkillCategory>
    </Skills>

    <!-- Projects developed and technologies used -->
    <Projects>
        <Project title="Khiffa Platform" duration="2024/07 – 2024/08">
            <Description>Delivery service platform integrated with other companies' systems.</Description>
            <Technologies>
                <Technology>Angular</Technology>
                <Technology>Bootstrap</Technology>
                <Technology>echarts</Technology>
            </Technologies>
            <Logo>assets/project-1.png</Logo> 
        </Project>
        <Project title="Nero App" duration="2023/10 – 2023/10">
            <Description>Rebuilding the company's app with added features.</Description>
            <Technologies>
                <Technology>Flutter</Technology>
                <Technology>Firebase</Technology>
            </Technologies>
            <Logo>assets/project-3.png</Logo> 
        </Project>
        <Project title="Etiqa'a" duration="2022/12 – 2023/02">
            <Description>Graduation project for monitoring WhatsApp messages for inappropriate content.</Description>
            <Technologies>
                <Technology>Flutter</Technology>
                <Technology>Flask</Technology>
                <Technology>MySQL</Technology>
            </Technologies>
            <Logo>assets/project-2.png</Logo> 
        </Project>
    </Projects>

    <!-- Publications -->
    <Publications>
        <Publication title="Etiqa'a: An Android Mobile Application for Monitoring Teen's Private Messages on WhatsApp" 
        journal="Engineering, Technology And Applied Science Research (ETASR)" 
        volume="13" number="6" year="2023">
        </Publication>
    </Publications>

    <!-- Volunteering initiatives -->
    <Volunteering>
        <Role organization="Ghali Center - Umm Al-Qura University" year="2021">Writer</Role>
        <Initiative>(Kateb) initiative to convert school curricula into Word format for Braille printing support.</Initiative>
    </Volunteering>
</Portfolio>
